"""Copy small batch stats into git-tracked reports. Never copies events or GIFs."""

from __future__ import annotations

import shutil
from datetime import datetime, timezone
from pathlib import Path

from emergence_lab.simulation.runner import git_commit

PUBLISH_NAMES = (
    "aggregate.md",
    "all_metrics.csv",
    "by_controller.csv",
    "paired_deltas.csv",
)

NOTES_TEMPLATE = """# Notes — `{batch_id}`

Numbers live in `aggregate.md` (generated, do not edit). This file is interpretation only.

A visually interesting GIF is not evidence of emergence.

**Status:** pending interpretation

Fill in after reading `aggregate.md`:

- What the numbers show (survival, births, generations) — no intelligence claims
- What they do **not** show
- Decision for the next run
"""


def project_root() -> Path:
    return Path(__file__).resolve().parents[3]


def default_reports_dir() -> Path:
    return project_root() / "experiments" / "reports"


def default_lab_log() -> Path:
    return project_root() / "docs" / "lab_log.md"


def publish_report(
    stats_dir: str | Path,
    *,
    reports_dir: str | Path | None = None,
    lab_log: str | Path | None = None,
    batch_id: str | None = None,
) -> Path:
    """Copy generated stats into experiments/reports/<batch_id>/.

    Creates NOTES.md and a lab-log stub only if they do not already exist,
    so later interpretation is never overwritten.
    """
    src = Path(stats_dir)
    name = batch_id or src.name
    dest = Path(reports_dir) if reports_dir else default_reports_dir()
    dest = dest / name
    dest.mkdir(parents=True, exist_ok=True)
    copied = []
    for filename in PUBLISH_NAMES:
        path = src / filename
        if path.is_file():
            shutil.copy2(path, dest / filename)
            copied.append(filename)
    notes = dest / "NOTES.md"
    if not notes.exists():
        notes.write_text(NOTES_TEMPLATE.format(batch_id=name), encoding="utf-8")
    _ensure_lab_log_stub(name, dest, Path(lab_log) if lab_log else default_lab_log())
    if not copied:
        raise FileNotFoundError(f"No publishable stats in {src}")
    return dest


def _ensure_lab_log_stub(batch_id: str, report_dir: Path, lab_log: Path) -> None:
    marker = f"— `{batch_id}`"
    if lab_log.exists() and marker in lab_log.read_text(encoding="utf-8"):
        return
    lab_log.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    commit = git_commit() or "—"
    rel = report_dir.as_posix()
    root = project_root()
    try:
        rel = str(report_dir.resolve().relative_to(root))
    except ValueError:
        pass
    stub = (
        f"\n## {stamp} — `{batch_id}`\n\n"
        f"- **Git:** `{commit}`\n"
        f"- **Report:** [{rel}/]({rel}/)\n"
        f"- **Numbers:** generated by `summarize` (see `aggregate.md`)\n"
        f"- **Interpretation:** pending (edit this entry and `{rel}/NOTES.md`)\n"
    )
    if lab_log.exists():
        lab_log.write_text(lab_log.read_text(encoding="utf-8") + stub, encoding="utf-8")
    else:
        lab_log.write_text(
            "# Lab log\n\n"
            "Chronological experiment record. Numbers are generated; interpretation is added after each batch.\n"
            "Raw runs stay in `experiments/results/` (gitignored).\n"
            + stub,
            encoding="utf-8",
        )
